title: Visas Meet
description: A social platform for Travelers, Immigrants, International students, and Expats. Meet, chat, network, and find your community in a new or foreign country.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-avatar # plugin to display GitHub user avatars
- jekyll-mentions # plugin to mention users
collections:
  profiles:
    output: true
    permalink: /:collection/:path/

