website:
  name: 'Visas Meet'
  description: 'A social platform designed for travelers, immigrants, international students, and expats.'
  welcome_message: 'Welcome to Visas Meet, a social platform designed for travelers, immigrants, international students, and expats. Here, you can meet, chat, network, date, and connect with people from all over the world. Whether you are in a new or foreign country, or simply looking to broaden your horizons, Visas Meet is the place for you.'
  logo: 'Link_to_your_logo_here'
  google_analytics: 'Your_Google_Analytics_ID'
  theme: 'jekyll-theme-cayman' # Changed to a more suitable theme
  remote_theme: 'pages-themes/cayman@v0.1.1'
  plugins:
    - 'jekyll-remote-theme' 
    - 'jekyll-avatar' 
    - 'jekyll-mentions' 
    - 'jekyll-paginate' # For pagination
    - 'jekyll-seo-tag' # For SEO optimization
    - 'jekyll-sitemap' # To generate a sitemap.xml for better SEO
  collections:
    profiles:
      output: true
      permalink: '/:collection/:path/'
    posts:
      output: true
      permalink: '/:collection/:path/'
  paginate: 5 # Posts per page
  exclude: ["README.md", "Gemfile", "Gemfile.lock"]
  features:
    - name: 'Meet'
      description: 'Find other individuals in your area and connect with them.'
    - name: 'Chat'
      description: 'Enjoy real-time conversations with your connections.'
    - name: 'Date'
      description: 'Explore potential relationships with other users.'
    - name: 'Network'
      description: 'Build a professional network and connect with potential employers or colleagues.'
    - name: 'Events'
      description: 'Attend virtual and real-life events and meetups organized by our community.'
  join_us: 'Getting started with Visas Meet is easy. Simply click the sign-up button and create your account. You can also sign up with your Facebook or Google account for a more streamlined process.'
  community: 'We are a diverse and inclusive community. Whether you are an expat looking for friends, a student studying abroad, or a traveler eager to connect with locals, you'll find a welcoming community at Visas Meet.'
  support:
    support_page: 'Link_to_your_support_page_here'
    email: 'support@visasmeet.com'
  social_media:
    - platform: 'Facebook'
      link: '#'
    - platform: 'Twitter'
      link: '#'
    - platform: 'Instagram'
      link: '#'
  license: 'Link_to_your_license_here'
